.TH XSYSTRACE "1" "November 2002"
.SH NAME
xsystrace \- systrace frontend invoked by systrace
.SH SYNOPSIS
.B xsystrace
.SH DESCRIPTION
\fBxsystrace\fP is normaly executed directly from systrace and should
not be called directly.
.PP
\fBxsystrace\fP runs in interactive mode and
creates the rules based on the inputs and selections in this frontend.
It is also a GUI to help creating permit or deny rules for systrace templates.
.SH SEE ALSO
.TP
systrace(1)
.SH AUTHOR
This manual page was written by Thorsten Sauter <tsauter@gmx.net>,
for the Debian GNU/Linux system (but may be used by others).
