/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_systracewin (void)
{
  GtkWidget *systracewin;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *pixmap6;
  GtkWidget *vseparator1;
  GtkWidget *timeline;
  GtkWidget *hbox2;
  GtkWidget *frame1;
  GtkWidget *vbox2;
  GtkWidget *hbox4;
  GtkWidget *processlabel;
  GtkWidget *processname;
  GtkWidget *hbox5;
  GtkWidget *label7;
  GtkWidget *processid;
  GtkWidget *hbox17;
  GtkWidget *label17;
  GtkWidget *policyname;
  GtkWidget *frame2;
  GtkWidget *vbox4;
  GtkWidget *syscallinfo;
  GtkWidget *hbox6;
  GtkWidget *label10;
  GtkWidget *filterentry;
  GtkWidget *combo_entry2;
  GtkWidget *wizardbutton;
  GtkWidget *frame3;
  GtkWidget *statusline;
  GtkWidget *hbox12;
  GtkWidget *frame4;
  GtkWidget *errorcode;
  GList *errorcode_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *vbox5;
  GtkWidget *frame5;
  GtkWidget *hbox13;
  GtkWidget *killbutton;
  GtkWidget *hbox16;
  GtkWidget *pixmap8;
  GtkWidget *label16;
  GtkWidget *reviewbutton;
  GtkWidget *detachbutton;
  GtkWidget *detachlabel;
  GtkWidget *hseparator1;
  GtkWidget *hbox7;
  GtkWidget *button2;
  GtkWidget *hbox8;
  GtkWidget *pixmap2;
  GtkWidget *label12;
  GtkWidget *button3;
  GtkWidget *hbox9;
  GtkWidget *pixmap3;
  GtkWidget *label13;
  GtkWidget *vseparator2;
  GtkWidget *button4;
  GtkWidget *hbox11;
  GtkWidget *pixmap5;
  GtkWidget *label15;
  GtkWidget *button5;
  GtkWidget *hbox10;
  GtkWidget *pixmap4;
  GtkWidget *label14;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  systracewin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (systracewin), "systracewin", systracewin);
  gtk_container_set_border_width (GTK_CONTAINER (systracewin), 3);
  gtk_window_set_title (GTK_WINDOW (systracewin), "Systrace Notification");
  gtk_window_set_position (GTK_WINDOW (systracewin), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (systracewin), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 4);

  pixmap6 = create_pixmap (systracewin, "logo.xpm");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap6, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (pixmap6), 0, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vseparator1", vseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox1), vseparator1, TRUE, TRUE, 0);

  timeline = gtk_label_new ("Time: XX-XX-XX");
  gtk_widget_ref (timeline);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "timeline", timeline,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (timeline);
  gtk_box_pack_start (GTK_BOX (hbox1), timeline, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (timeline), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (timeline), 0.5, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 4);

  frame1 = gtk_frame_new ("Process Information");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox2), frame1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame1), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 1);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, TRUE, TRUE, 0);

  processlabel = gtk_label_new ("Process-Name:");
  gtk_widget_ref (processlabel);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "processlabel", processlabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (processlabel);
  gtk_box_pack_start (GTK_BOX (hbox4), processlabel, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (processlabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (processlabel), 4, 0);

  processname = gtk_label_new ("/usr/local/bin/konq-e");
  gtk_widget_ref (processname);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "processname", processname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (processname);
  gtk_box_pack_start (GTK_BOX (hbox4), processname, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (processname), GTK_JUSTIFY_LEFT);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox5, TRUE, TRUE, 0);

  label7 = gtk_label_new ("Process-Pid:");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label7), 4, 0);

  processid = gtk_label_new ("27344");
  gtk_widget_ref (processid);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "processid", processid,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (processid);
  gtk_box_pack_start (GTK_BOX (hbox5), processid, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox17);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox17", hbox17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox17, TRUE, TRUE, 0);

  label17 = gtk_label_new ("Policy-Name:");
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox17), label17, FALSE, FALSE, 0);

  policyname = gtk_label_new ("/usr/local/bin/konq-e");
  gtk_widget_ref (policyname);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "policyname", policyname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (policyname);
  gtk_box_pack_start (GTK_BOX (hbox17), policyname, FALSE, FALSE, 0);

  frame2 = gtk_frame_new ("System Call Information");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame2), vbox4);

  syscallinfo = gtk_label_new ("native-open: filename: blah, open-flags: blah");
  gtk_widget_ref (syscallinfo);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "syscallinfo", syscallinfo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (syscallinfo);
  gtk_box_pack_start (GTK_BOX (vbox4), syscallinfo, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (syscallinfo), TRUE);
  gtk_misc_set_padding (GTK_MISC (syscallinfo), 4, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, TRUE, TRUE, 0);

  label10 = gtk_label_new ("Filter Expression:");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  filterentry = gtk_combo_new ();
  gtk_widget_ref (filterentry);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "filterentry", filterentry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (filterentry);
  gtk_box_pack_start (GTK_BOX (hbox6), filterentry, TRUE, TRUE, 0);

  combo_entry2 = GTK_COMBO (filterentry)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  wizardbutton = gtk_button_new_with_label ("Wizard");
  gtk_widget_ref (wizardbutton);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "wizardbutton", wizardbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wizardbutton);
  gtk_box_pack_start (GTK_BOX (hbox6), wizardbutton, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (wizardbutton), 3);

  frame3 = gtk_frame_new ("Status");
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox1), frame3, TRUE, TRUE, 4);

  statusline = gtk_label_new ("label16");
  gtk_widget_ref (statusline);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "statusline", statusline,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusline);
  gtk_container_add (GTK_CONTAINER (frame3), statusline);
  gtk_misc_set_padding (GTK_MISC (statusline), 0, 2);

  hbox12 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox12);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox12", hbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox12, TRUE, TRUE, 2);

  frame4 = gtk_frame_new ("Error Code");
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (hbox12), frame4, TRUE, TRUE, 0);

  errorcode = gtk_combo_new ();
  gtk_widget_ref (errorcode);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "errorcode", errorcode,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (errorcode);
  gtk_container_add (GTK_CONTAINER (frame4), errorcode);
  gtk_combo_set_value_in_list (GTK_COMBO (errorcode), TRUE, FALSE);
  errorcode_items = g_list_append (errorcode_items, (gpointer) "eperm");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "enoent");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "einval");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "enotdir");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "eio");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "enxio");
  errorcode_items = g_list_append (errorcode_items, (gpointer) "eacces");
  gtk_combo_set_popdown_strings (GTK_COMBO (errorcode), errorcode_items);
  g_list_free (errorcode_items);

  combo_entry1 = GTK_COMBO (errorcode)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_tooltips_set_tip (tooltips, combo_entry1, "Configures the error code that is being returned to the application.  This error code is used when a system call is denied.", NULL);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), "eperm");

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox5, TRUE, TRUE, 0);

  frame5 = gtk_frame_new ("Special Processing");
  gtk_widget_ref (frame5);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "frame5", frame5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox5), frame5, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (frame5), hbox13);
  gtk_container_set_border_width (GTK_CONTAINER (hbox13), 2);

  killbutton = gtk_button_new ();
  gtk_widget_ref (killbutton);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "killbutton", killbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (killbutton);
  gtk_box_pack_start (GTK_BOX (hbox13), killbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, killbutton, "The current process is terminated with this button.", NULL);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox16);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox16", hbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (killbutton), hbox16);

  pixmap8 = create_pixmap (systracewin, "skull.xpm");
  gtk_widget_ref (pixmap8);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap8", pixmap8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap8);
  gtk_box_pack_start (GTK_BOX (hbox16), pixmap8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (pixmap8), 0, 0);

  label16 = gtk_label_new ("Kill");
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox16), label16, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label16), 2, 0);

  reviewbutton = gtk_button_new_with_label ("Review Filter");
  gtk_widget_ref (reviewbutton);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "reviewbutton", reviewbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reviewbutton);
  gtk_box_pack_start (GTK_BOX (hbox13), reviewbutton, FALSE, FALSE, 2);
  gtk_tooltips_set_tip (tooltips, reviewbutton, "The currently configured poloicy for this system call can be reviewed.", NULL);

  detachbutton = gtk_button_new ();
  gtk_widget_ref (detachbutton);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "detachbutton", detachbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (detachbutton);
  gtk_box_pack_start (GTK_BOX (hbox13), detachbutton, FALSE, FALSE, 2);
  gtk_tooltips_set_tip (tooltips, detachbutton, "Detaches the interactive monitoring from the current policy.  If a policy exists, all system calls not covered by it will be denied. Otherwise, if no policy exists, all system calls for this process will be allowed.", NULL);

  detachlabel = gtk_label_new ("Detach");
  gtk_widget_ref (detachlabel);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "detachlabel", detachlabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (detachlabel);
  gtk_container_add (GTK_CONTAINER (detachbutton), detachlabel);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 0);

  hbox7 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox7, TRUE, TRUE, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (hbox7), button2, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button2, "Denies the current system call.  The error code above is returned to the application.  The application is allowed to attempt the system call again.", NULL);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (button2), hbox8);

  pixmap2 = create_pixmap (systracewin, "deny.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox8), pixmap2, TRUE, TRUE, 0);

  label12 = gtk_label_new ("Deny");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox8), label12, TRUE, TRUE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label12), TRUE);
  gtk_misc_set_padding (GTK_MISC (label12), 2, 0);

  button3 = gtk_button_new ();
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox7), button3, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button3, "Allows the current system call.  If the application attempts the system call again, a new warning will be generated.", NULL);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (button3), hbox9);

  pixmap3 = create_pixmap (systracewin, "permit.xpm");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox9), pixmap3, TRUE, TRUE, 0);

  label13 = gtk_label_new ("Permit");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, TRUE, TRUE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label13), TRUE);
  gtk_misc_set_padding (GTK_MISC (label13), 2, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator2);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "vseparator2", vseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator2);
  gtk_box_pack_start (GTK_BOX (hbox7), vseparator2, TRUE, TRUE, 0);

  button4 = gtk_button_new ();
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox7), button4, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button4, "Denies the application to execute the system call ever again.  The error configured above will be returned.  No warning for this system call will be generated again.  Use carefully.", NULL);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox11);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox11", hbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (button4), hbox11);

  pixmap5 = create_pixmap (systracewin, "deny-always.xpm");
  gtk_widget_ref (pixmap5);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap5", pixmap5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap5);
  gtk_box_pack_start (GTK_BOX (hbox11), pixmap5, TRUE, TRUE, 0);

  label15 = gtk_label_new ("Deny\nAlways");
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox11), label15, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);
  gtk_misc_set_padding (GTK_MISC (label15), 2, 0);

  button5 = gtk_button_new ();
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox7), button5, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button5, "Permit this system call forever.  No more monitoring of this system call is happening.  No more warnings will be generated.  Use this very carefully.", NULL);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox10);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (button5), hbox10);

  pixmap4 = create_pixmap (systracewin, "permit-always.xpm");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox10), pixmap4, TRUE, TRUE, 0);

  label14 = gtk_label_new ("Permit\nAlways");
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (systracewin), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label14), TRUE);
  gtk_misc_set_padding (GTK_MISC (label14), 2, 0);

  gtk_signal_connect (GTK_OBJECT (combo_entry2), "activate",
                      GTK_SIGNAL_FUNC (on_filterentry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wizardbutton), "clicked",
                      GTK_SIGNAL_FUNC (on_wizard_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (killbutton), "clicked",
                      GTK_SIGNAL_FUNC (on_killbutton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reviewbutton), "clicked",
                      GTK_SIGNAL_FUNC (on_reviewbutton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (detachbutton), "clicked",
                      GTK_SIGNAL_FUNC (on_detachbutton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_denyonce_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_permitonce_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_deny_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_permit_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (systracewin), "tooltips", tooltips);

  return systracewin;
}

GtkWidget*
create_filterreview (void)
{
  GtkWidget *filterreview;
  GtkWidget *vbox6;
  GtkWidget *hbox14;
  GtkWidget *pixmap7;
  GtkWidget *frame6;
  GtkWidget *filterlist;
  GtkWidget *hbox15;
  GtkWidget *okbutton;

  filterreview = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (filterreview), "filterreview", filterreview);
  gtk_window_set_title (GTK_WINDOW (filterreview), "Systrace - Filter Review");
  gtk_window_set_modal (GTK_WINDOW (filterreview), TRUE);

  vbox6 = gtk_vbox_new (FALSE, 2);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (filterreview), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 4);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox14, TRUE, TRUE, 0);

  pixmap7 = create_pixmap (filterreview, "logo.xpm");
  gtk_widget_ref (pixmap7);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "pixmap7", pixmap7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap7);
  gtk_box_pack_start (GTK_BOX (hbox14), pixmap7, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (pixmap7), 0, 0);

  frame6 = gtk_frame_new ("Filter List");
  gtk_widget_ref (frame6);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "frame6", frame6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox6), frame6, TRUE, TRUE, 0);

  filterlist = gtk_list_new ();
  gtk_widget_ref (filterlist);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "filterlist", filterlist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (filterlist);
  gtk_container_add (GTK_CONTAINER (frame6), filterlist);
  gtk_container_set_border_width (GTK_CONTAINER (filterlist), 2);
  gtk_list_set_selection_mode (GTK_LIST (filterlist), GTK_SELECTION_BROWSE);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox15, TRUE, TRUE, 0);

  okbutton = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (okbutton);
  gtk_object_set_data_full (GTK_OBJECT (filterreview), "okbutton", okbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (okbutton);
  gtk_box_pack_start (GTK_BOX (hbox15), okbutton, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (okbutton), "clicked",
                      GTK_SIGNAL_FUNC (on_okbutton_clicked),
                      NULL);

  return filterreview;
}

GtkWidget*
create_wizard (void)
{
  GtkWidget *wizard;
  GtkWidget *vbox7;
  GtkWidget *hbox18;
  GtkWidget *pixmap9;
  GtkWidget *hseparator2;
  GtkWidget *label18;
  GtkWidget *hbox20;
  GtkWidget *templates;
  GtkWidget *wizardlist;
  GtkWidget *frame7;
  GtkWidget *description;
  GtkWidget *hbox19;
  GtkWidget *button6;
  GtkWidget *wizard_cancel;

  wizard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (wizard), "wizard", wizard);
  gtk_window_set_title (GTK_WINDOW (wizard), "Systrace - Wizard");
  gtk_window_set_position (GTK_WINDOW (wizard), GTK_WIN_POS_MOUSE);
  gtk_window_set_default_size (GTK_WINDOW (wizard), 400, -1);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (wizard), vbox7);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox18);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "hbox18", hbox18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox18, TRUE, TRUE, 0);

  pixmap9 = create_pixmap (wizard, "logo.xpm");
  gtk_widget_ref (pixmap9);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "pixmap9", pixmap9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap9);
  gtk_box_pack_start (GTK_BOX (hbox18), pixmap9, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox7), hseparator2, FALSE, FALSE, 0);

  label18 = gtk_label_new ("This dialog allows the selection of default policies for the current application. The following list describes potential templates that can be used as a quick start for a new policy.");
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (vbox7), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label18), TRUE);
  gtk_misc_set_padding (GTK_MISC (label18), 4, 4);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox20);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "hbox20", hbox20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox20, FALSE, FALSE, 0);

  templates = gtk_frame_new ("Templates");
  gtk_widget_ref (templates);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "templates", templates,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (templates);
  gtk_box_pack_start (GTK_BOX (hbox20), templates, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (templates), 2);

  wizardlist = gtk_list_new ();
  gtk_widget_ref (wizardlist);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "wizardlist", wizardlist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wizardlist);
  gtk_container_add (GTK_CONTAINER (templates), wizardlist);
  gtk_container_set_border_width (GTK_CONTAINER (wizardlist), 4);

  frame7 = gtk_frame_new ("Description");
  gtk_widget_ref (frame7);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "frame7", frame7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (hbox20), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 2);

  description = gtk_label_new ("This describes the purpose of the current template.");
  gtk_widget_ref (description);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "description", description,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (description);
  gtk_container_add (GTK_CONTAINER (frame7), description);
  gtk_label_set_justify (GTK_LABEL (description), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (description), TRUE);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox19);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "hbox19", hbox19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox19, FALSE, FALSE, 0);

  button6 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox19), button6, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button6), 2);

  wizard_cancel = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (wizard_cancel);
  gtk_object_set_data_full (GTK_OBJECT (wizard), "wizard_cancel", wizard_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (wizard_cancel);
  gtk_box_pack_start (GTK_BOX (hbox19), wizard_cancel, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (wizard_cancel), 2);

  gtk_signal_connect (GTK_OBJECT (wizardlist), "select_child",
                      GTK_SIGNAL_FUNC (on_wizardlist_select_child),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (template_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (wizard_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_wizard_cancel_clicked),
                      NULL);

  return wizard;
}

